"""Constants for app."""

LIMIT_USERNAME_LENGTH = 150
LIMIT_USER_BIO_LENGTH = 254
LIMIT_USER_EMAIL_LENGTH = 254
LIMIT_USER_ROLE_LENTGH = 25
LIMIT_NAME_LENGHT = 150
LIMIT_CATEGORY_NAME = 256
LIMIT_GENRE_NAME = 256
TITLE_LIMIT = 30
